### ISSUE TITLE
[To discuss] Request Approval – Process

### ISSUE THREAD

**Issue by devanshah1991** [hindsight-io/connect#111]
So we need to make sure this works golden. A user submits a request to an advisor. An advisor should get an email notification with the details as well as a "new Request” notification above the Connections tab. Then, an advisor reviews the request and if he accepts, the user gets a notification that he accepted (email and above the notifications), and that the user should begin to upload documents (along with complete payment info immediately). The approval of a request should also automatically start a chat between the user and the advisor that starts off with an automatic “XYZ has approved your request. Begin uploading your documents and schedule discussion times with XYZ here”

**Comment by dax0** [comment]
Moved to #138
