### ISSUE TITLE
Profiles & Names – Preserving Anonymity  / Privacy

### ISSUE THREAD

**Issue by devanshah1991** [hindsight-io/connect#112]
Is it easy to make sure that all names of advisors and users only show up as “Devan S.” “Mukund K.” everywhere (profiles, Q&A Panel, messages), to be consistent and protect private

**Comment by julioreynaga** [comment]
think this one is done for all new profiles created right? It's only the old profiles for example the one from Dax that shows up with the last name because that was the default before

**Comment by dax0** [comment]
Yeah all new profiles will be fixed, I'll go manually fix the old ones as well
