### ISSUE TITLE
Request - Changing to Request Time Estimate

### ISSUE THREAD

**Issue by julioreynaga** [hindsight-io/connect#116]
We are replacing the suggested price data point for "Request Time Estimate" to avoid giving a price point for now to see more transactions go through at people's own budget. We will just give them guidance of time as we mentioned earlier. So only the wording would change to "Request Time Estimate" and the formula would now be:

Request Time Estimate = + (Video Call Minutes) + (Total Essay Words*120/600)

The format output of the time ideally would be: "1 h 40 min" if easy, otherwise in minutes for now

**Comment by dax0** [comment]
What about resume editing?

**Comment by julioreynaga** [comment]
Right, 90 minutes for the resume review, so Request Time Estimate = + (Video Call Minutes) + (Total Essay Words*120/600) + (Resume Variable*90)
