### ISSUE TITLE
Creating accounts for previous members & mentors

### ISSUE THREAD

**Issue by julioreynaga** [hindsight-io/connect#118]
Let us know once the accounts are created and we can go to their accounts and fill the information and recreate the Q&A/messages.

We can use a common password that they can then change. We will email them this password so maybe we can use something that seems customized even though all of them have the same

**Comment by dax0** [comment]
Did you send me the Excel file?

**Comment by julioreynaga** [comment]
we sent it on slack, we couldn't upload it here
