### ISSUE TITLE
Edit Profile - Screen name 

### ISSUE THREAD

**Issue by julioreynaga** [hindsight-io/connect#121]
If you change the First Name and Last Name on the "Edit Profile" option on the top corner, the screen name does not update

**Comment by julioreynaga** [comment]
It seems that the screen name does not update in the (a) Inbox tabs, (b) the strip profiles (if you are an advisor), (c) if you post a question on the panel ( in the page where you see all the questions before clicking on one). In those I'm still Julio R2. It works and updates automatically on the main profile and on the question-specific page.

**Comment by dax0** [comment]
It's because you have a full name set from the previous version. I'll reset
it manually

**Comment by julioreynaga** [comment]
ah okok perfect, no worries
