### ISSUE TITLE
Upload documents - Bug in firefox & microsoft edge

### ISSUE THREAD

**Issue by julioreynaga** [hindsight-io/connect#122]
In firefox, I can't upload documents to the message chat. 

In microsoft edge you can upload files, but after a few seconds it disappears. You need to logout and login again to see the upload document. Just updating the page or changing tabs does not work

It works perfectly for me on Chrome

**Comment by dax0** [comment]
Fixed in FFOX

**Comment by dax0** [comment]
Fixed Edge bug
