### ISSUE TITLE
Request - Bug on information submitted on request

### ISSUE THREAD

**Issue by julioreynaga** [hindsight-io/connect#126]
Some of the info from the request does not go through to the summary request that ppl see on Dashboard/Connections, in particular : 
1. Degree
2. Information on the type of call that users select from the check marks below Video Call minutes (Essay/Resume Review Comments Discussion, etc)
3. Can we get the numbers of Essay 1,2,3,4,5 on the summary request or the total number of essays super easy? (just don't want mentors to think it's a glitch if 2 essays have the same words)

**Comment by dax0** [comment]
Fixed 1 and 3 going to move 2 to a separate issue to be dealt with later.  I thought those checkmarks were purely cosmetic so users could get an idea what the calls could be used for
