### ISSUE TITLE
We should remove “High School” and “Any” from the categories in the Q&A, only the 4 key categories should be there

### ISSUE THREAD

**Issue by julioreynaga** [hindsight-io/connect#29]

**Comment by dax0** [comment]
Are we sure we don't want to leave 'Any' in for generic questions

**Comment by devanshah1991** [comment]
Dax, what do you think about this. High schooler's only care about the undergrad forum, potential MBA's only care about the MBA forum. High school kids will never be on the MBA forum, etc. Mixing the forums together makes things harder to navigate and more confusing and unnecessary. Can we separate out the forums? So, when you go to the Ask tab, maybe a hover down option asks you which forum you want to go to - the undergrad, MBA, med, or law (like we have it on the current hindsight.io). Another option is to first click the Ask tab, and once that loads, it asks you, which forum do you want to go to, and you choose. I think the first option is better cause it involves one less step, but let me know what you think.
