### ISSUE TITLE
Landing Page Discussion

### ISSUE THREAD

**Issue by dax0** [hindsight-io/connect#3]

**Comment by julioreynaga** [comment]
Is there a particular landing page format that you have to use? If you send as a sample we can adjust the content to that. We could keep the current landing page for now just to get the new website going. Just let us know if you have an example of something you think is simple / effective

We will send a basic how services work tab/info with basic descriptions for people to understand the offerings and the request process

**Comment by dax0** [comment]
I was planning on keeping the current page for now and just changing where
the top buttons link out to

**Comment by julioreynaga** [comment]
ok yeah that works for now, page has been working well thus far
