### ISSUE TITLE
Left Profile Size

### ISSUE THREAD

**Issue by dax0** [hindsight-io/connect#4]
I didn't change the size of it, not too sure why it's appearing skinny on your computer I'll take a look

**Comment by dax0** [comment]
@julioreynaga @Mukund91 Can you guys double check this to see if you can figure out what situation it occurs

**Comment by julioreynaga** [comment]
this looks good now in both of our laptops, not sure what happened before

**Comment by dax0** [comment]
Okay I'll close this for now then
