### ISSUE TITLE
Product Request: Part A) Requesting a Service

### ISSUE THREAD

**Issue by devanshah1991** [hindsight-io/connect#40]
You can request a service from any advisor. Go to that individual's page, and request whatever you want. No credit card info is needed yet. The advisor should get an email notification of the service request (the email should include the $ amount of the request as well). The advisor has 48 hours to accept / reject. If the advisor accepts, the process begins and then the customer is prompted to put in his/her credit card info (customers gets an email notification of this). If the advisor rejects, perhaps he can put in a text reason for rejections ("I'll do it for $150 instead," "sorry, very busy ATM"), etc, and the customer gets an email notification along with the rejection reason. 

Now, the advisor should get an email reminder at least every 12 hours that he as a request pending for $X amount. If the advisor doesn't respond within 48 hours, the request is terminated and the customer again is notified of this. I would hate to lose customers this way, so we should be able to keep tabs on inactive advisors who haven't yet responded to service requests in the admin panel

**Comment by dax0** [comment]
So to clarify the only thing to add is the 12 hour reminder

**Comment by devanshah1991** [comment]
if we've already done everything else, then yeah. just thought about that today since it makes sense. And, of course, the email notifcaiton should say request for $XXX so we shove the money component in the advisors face

**Comment by dax0** [comment]
Got it
