### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by devanshah1991** [hindsight-io/connect#94]
When entering Music or Athletics to the Extracurricular timeline, you don't get the "Category" in the timeline (only the activity name)

**Comment by dax0** [comment]
Is this still an issue? Thought I fixed it

**Comment by devanshah1991** [comment]
nah dude if you try it on your timeline you'll see theres a few of them that just dont show up, i think academics as well, i'm sure there are a few others

**Comment by dax0** [comment]
Was able to add it on mine: http://connect.hindsight.io/profile/d6fd5bd4-b309-499e-ba2f-053dd4cd1650

I switched us to production mode so deploys happen slower now you may be on an older version

**Comment by devanshah1991** [comment]
that possible..for example, just looked at your profile and you don't even have anything on your extracurricular timeline. you just have one thing for education

**Comment by julioreynaga** [comment]
Just to clarify, @dax0  here the minor thing was that for example on your profile for "Hacker" here you have "Computer/tech" but for "Basketball" you don't have "Athletics" (the category) below only the Activity name, same happens for "Music" (the word "Music" doesn't appear). Those are the only 2 that have the issue, the rest are ok

hacker
Computer/technology
Position: Mr. Robot

Unknown - Current
Basketball
Position:
